SET CONFIGENVWEBSERVICESRETURNCODE=0
cd %~dp0..\..\..\..
SET WYNSURERESOURCESFOLDER=%CD%
cd ..
IF NOT %ERRORLEVEL%==0 SET CONFIGENVWEBSERVICESRETURNCODE=%ERRORLEVEL%
IF EXIST "Dev\bin\eWam Set Env.bat" CALL "Dev\bin\eWam Set Env.bat"
IF NOT %ERRORLEVEL%==0 SET CONFIGENVWEBSERVICESRETURNCODE=%ERRORLEVEL%
IF NOT EXIST "Dev\bin\eWam Set Env.bat" IF EXIST "%WYNSURERESOURCESFOLDER%\bin\eWam Set Env.bat" CALL "%WYNSURERESOURCESFOLDER%\bin\eWam Set Env.bat"
IF NOT %ERRORLEVEL%==0 SET CONFIGENVWEBSERVICESRETURNCODE=%ERRORLEVEL%
IF NOT EXIST "Dev\bin\eWam Set Env.bat" IF NOT EXIST "%WYNSURERESOURCESFOLDER%\bin\eWam Set Env.bat" CALL EWAMSETENVNOTFOUND

IF NOT %CONFIGENVWEBSERVICESRETURNCODE%==0 GOTO ENDINERROR

::set SERVER_PORT_STR={SERVER_PORT_WS}
set GSP_SUFFIX=_%PRODUCTNAME%
set GSP_ALIAS=GSP%PRODUCTNAME%
set APPCMD=%windir%\system32\inetsrv\appcmd.exe

SET INSTALLWEBSITEROOTFOLDER=%WF-ROOT%\integration\WebSiteInstall
SET CONFIGGSPSOURCE=%INSTALLWEBSITEROOTFOLDER%\files\ConfigFiles\GSP
SET CONFIGWSMFRSOURCE=%INSTALLWEBSITEROOTFOLDER%\files\ConfigFiles\WSM\FR
SET CONFIGWSMENSOURCE=%INSTALLWEBSITEROOTFOLDER%\files\ConfigFiles\WSM\EN
SET ROOTWEBSITESFOLDER=%ENV-ROOT%\inetpub
set SITEDIR=%WF-ROOT%\inetpub\wwwroot
set GSPFOLDERSOURCE=%WYDE-ROOT%\Dll
set GSPFOLDERTARGET=%SITEDIR%\GSP%GSP_SUFFIX%
set GSPDLL=%GSPFOLDERTARGET%\GSP.dll
set VIRTUAL_DIR=%SITEDIR%
set BATCH=%INSTALLWEBSITEROOTFOLDER%\files\batch
GOTO END

:EWAMSETENVNOTFOUND
ECHO #ERROR# File "eWam Set Env.bat" not found, please check and retry (not found nor on Dev\bin\ neither on "%WYNSURERESOURCESFOLDER%\bin)
SET CONFIGENVWEBSERVICESRETURNCODE=1
GOTO :EOF

:ENDINERROR
ECHO #ERROR# Error level %CONFIGENVWEBSERVICESRETURNCODE%, please check and retry
GOTO END

:END
EXIT /B %CONFIGENVWEBSERVICESRETURNCODE%