SET PRODUCTNAME=ClickOnce
SET CLICKONCERESOURCES=%WF-ROOT%\Integration\WebSiteInstall\files\resources\ClickOnce
set GSP_HANDLER_EXT=*.html
set GSP_HANDLER_NAME=HTML_GSP

SET CONFIGENVWPORTALRETURNCODE=0
cd %~dp0..\..\..\..
SET WYNSURERESOURCESFOLDER=%CD%
cd ..
IF NOT %ERRORLEVEL%==0 SET CONFIGENVWPORTALRETURNCODE=%ERRORLEVEL%
SET EWAMSETENVALREADYDONE=false
IF EXIST "Dev\bin\eWam Set Env.bat" CALL "Dev\bin\eWam Set Env.bat"
IF NOT %ERRORLEVEL%==0 SET CONFIGENVWPORTALRETURNCODE=%ERRORLEVEL%
IF NOT EXIST "Dev\bin\eWam Set Env.bat" IF EXIST "%WYNSURERESOURCESFOLDER%\bin\eWam Set Env.bat" CALL "%WYNSURERESOURCESFOLDER%\bin\eWam Set Env.bat"
IF NOT EXIST "Dev\bin\eWam Set Env.bat" IF NOT EXIST "%WYNSURERESOURCESFOLDER%\bin\eWam Set Env.bat" IF EXIST "EnvRoot\bin\eWam Set Env.bat" CALL "EnvRoot\bin\eWam Set Env.bat"
echo WYDE-ROOT: %WYDE-ROOT%
echo WF-ROOT: %WF-ROOT%
echo ENV-ROOT: %ENV-ROOT%

::IF NOT %ERRORLEVEL%==0 SET CONFIGENVWPORTALRETURNCODE=%ERRORLEVEL%
::IF NOT EXIST "Dev\bin\eWam Set Env.bat" IF NOT EXIST "%WYNSURERESOURCESFOLDER%\bin\eWam Set Env.bat" GOTO EWAMSETENVNOTFOUND

IF NOT %CONFIGENVWPORTALRETURNCODE%==0 GOTO ENDINERROR

::set SERVER_PORT_STR={SERVER_PORT_GSP}
::set GSP_SUFFIX=_%PRODUCTNAME%
set APPCMD=%windir%\system32\inetsrv\appcmd.exe
SET INSTALLWPORTALROOTFOLDER=%WF-ROOT%\integration\WebSiteInstall
::SET CONFIGGSPSOURCE=%INSTALLWPORTALROOTFOLDER%\files\ConfigFiles\GSP
SET CONFIGWEBSITEFRSOURCE=%INSTALLWPORTALROOTFOLDER%\files\ConfigFiles\ClickOnce\Website\FR
SET CONFIGWEBSITEUSSOURCE=%INSTALLWPORTALROOTFOLDER%\files\ConfigFiles\ClickOnce\Website\US
SET CONFIGWSMSOURCE=%INSTALLWPORTALROOTFOLDER%\files\ConfigFiles\ClickOnce\Wyseman
SET ROOTWEBSITESFOLDER=%ENV-ROOT%\inetpub
::set SITEDIR=%ROOTWEBSITESFOLDER%\wwwroot_wWeb
set SITEDIRFR=%ROOTWEBSITESFOLDER%\ClickOnce_FR
set SITEDIRUS=%ROOTWEBSITESFOLDER%\ClickOnce_US
::set GSPFOLDERSOURCE=%WYDE-ROOT%\Dll
::set GSPFOLDERTARGET=%SITEDIR%
::set GSPDLL=%GSPFOLDERTARGET%\GSP.dll
::set VIRTUAL_DIR_LIST=client groupadmin broker wynsure demo
set BATCH=%INSTALLWPORTALROOTFOLDER%\files\batch
GOTO END

:EWAMSETENVNOTFOUND
ECHO #ERROR# File "eWam Set Env.bat" not found, please check and retry (not found nor on Dev\bin\ neither on "%WYNSURERESOURCESFOLDER%\bin")
SET CONFIGENVWPORTALRETURNCODE=1
GOTO :EOF

:ENDINERROR
ECHO #ERROR# Error level %CONFIGENVWPORTALRETURNCODE%, please check and retry
GOTO END

:END
EXIT /B %CONFIGENVWPORTALRETURNCODE%