SET COPYRESOURCESRETURNCODE=0
IF NOT "%COPYRESSOURCES%"=="Y" GOTO END

IF NOT EXIST "%SITEDIRFR%" CALL :COPYCLICKONCERESOURCESFR
IF NOT EXIST "%SITEDIRFUS%" CALL :COPYCLICKONCERESOURCESUS
IF EXIST "%SITEDIRFR%" ECHO #INFO# folder already "%SITEDIRFR%", no need to copy ClickOncce resources from "%CLICKONCERESOURCES%".
IF EXIST "%SITEDIRFUS%" ECHO #INFO# folder already "%SITEDIRUS%", no need to copy ClickOncce resources from "%CLICKONCERESOURCES%".
IF NOT EXIST "%CLICKONCERESOURCES%" GOTO SOURCENOTFOUND
GOTO END

:COPYCLICKONCERESOURCESFR
echo #INFO# Copying ClickOnce resources from "%CLICKONCERESOURCES%" to "%SITEDIRFR%"
IF NOT EXIST "%SITEDIRFR%" CALL :CREATEDIR "%SITEDIRFR%"
CALL :COPYFOLDERFR ClickOnceWydeWeb
CALL :COPYFOLDERFR Theme
CALL :COPYFOLDERFR WydeWebErrors
CALL :COPYFILES BrowserDetection.js "%SITEDIRFR%"
CALL :COPYFILES HelpChrome.html "%SITEDIRFR%"
CALL :COPYFILES HelpClickOnce.html "%SITEDIRFR%"
CALL :COPYFILES HelpFireFox.html "%SITEDIRFR%"
CALL :COPYFILES index.html "%SITEDIRFR%"
CALL :COPYFILES web.config "%SITEDIRFR%"
CALL :COPYFILES WydeClient.application "%SITEDIRFR%"
GOTO :EOF

:COPYCLICKONCERESOURCESUS
echo #INFO# Copying ClickOnce resources from "%CLICKONCERESOURCES%" to "%SITEDIRUS%"
IF NOT EXIST "%SITEDIRFUS%" CALL :CREATEDIR "%SITEDIRUS%"
CALL :COPYFOLDERUS ClickOnceWydeWeb
CALL :COPYFOLDERUS Theme
CALL :COPYFOLDERUS WydeWebErrors
CALL :COPYFILES BrowserDetection.js "%SITEDIRUS%"
CALL :COPYFILES HelpChrome.html "%SITEDIRUS%"
CALL :COPYFILES HelpClickOnce.html "%SITEDIRUS%"
CALL :COPYFILES HelpFireFox.html "%SITEDIRUS%"
CALL :COPYFILES index.html "%SITEDIRUS%"
CALL :COPYFILES web.config "%SITEDIRUS%"
CALL :COPYFILES WydeClient.application "%SITEDIRUS%"
GOTO :EOF

:CREATEDIR
ECHO #INFO# Creating folder %1
MKDIR %1
IF NOT %ERRORLEVEL%==0 SET COPYRESOURCESRETURNCODE=%ERRORLEVEL%
GOTO :EOF

:SOURCENOTFOUND
ECHO #ERROR# Source folder not found : "%CLICKONCERESOURCES%"
SET COPYRESOURCESRETURNCODE=1
GOTO END

:COPYFOLDERUS
ECHO Copying %1
robocopy "%CLICKONCERESOURCES%\%1" "%SITEDIRFR%\%1" /NDL /NFL /NP /R:5 /S >> %LOG% 2>&1
IF %ERRORLEVEL% GEQ 9 SET COPYRESOURCESRETURNCODE=%ERRORLEVEL%
GOTO :EOF

:COPYFOLDERFR
ECHO Copying %1
robocopy "%CLICKONCERESOURCES%\%1" "%SITEDIRUS%\%1" /NDL /NFL /NP /R:5 /S >> %LOG% 2>&1
IF %ERRORLEVEL% GEQ 9 SET COPYRESOURCESRETURNCODE=%ERRORLEVEL%
GOTO :EOF

:COPYFILES
ECHO Copying %1
robocopy "%CLICKONCERESOURCES%" %2 %1 /NDL /NFL /NP /R:5 /S >> %LOG% 2>&1
IF %ERRORLEVEL% GEQ 9 SET COPYRESOURCESRETURNCODE=%ERRORLEVEL%
GOTO :EOF

:END
exit /b %COPYRESOURCESRETURNCODE%
