SET COPYBINARIESRETURNCODE=0

echo #INFO# Copying GSP binaries from "%GSPFOLDERSOURCE%" to "%GSPFOLDERTARGET%"
IF NOT EXIST "%GSPFOLDERSOURCE%" GOTO SOURCENOTFOUND
IF NOT EXIST "%GSPFOLDERTARGET%" CALL :CREATEDIR "%GSPFOLDERTARGET%"
CALL :COPYFILE GSP.dll
CALL :COPYFILE msvcp100.dll
CALL :COPYFILE msvcr100.dll
CALL :COPYFILE sysmod.dll
CALL :COPYFILE wlib.dll
CALL :COPYFILE wpfbridge.dll
CALL :COPYFILE WySeManDll.dll
::CALL :COPYFILE OxyPlot.dll
::CALL :COPYFILE OxyPlot.Wpf.dll
::CALL :COPYFILE WSMISAPI.dll
::CALL :COPYFILE wWPFLib.dll
::CALL :COPYFILE Xceed.Wpf.Toolkit.dll

GOTO END

:CREATEDIR
ECHO #INFO# Creating folder %1
MKDIR %1
IF NOT %ERRORLEVEL%==0 SET COPYBINARIESRETURNCODE=%ERRORLEVEL%
GOTO :EOF

:SOURCENOTFOUND
ECHO #ERROR# Source folder not found : "%GSPFOLDERSOURCE%"
SET COPYBINARIESRETURNCODE=1
GOTO END

:COPYFILE
ECHO Copying %1
xcopy "%GSPFOLDERSOURCE%\%1" "%GSPFOLDERTARGET%" /E /R /C /I /Y /H /G >> %LOG% 2>&1
IF NOT %ERRORLEVEL%==0 SET COPYBINARIESRETURNCODE=%ERRORLEVEL%
GOTO :EOF

:END
ECHO #INFO# %~0 ended with return code %COPYBINARIESRETURNCODE%.
exit /b %COPYBINARIESRETURNCODE%
