echo Creating launchers

IF "%GSP_ALIAS%"=="" SET GSP_ALIAS=GSP

SET LAUNCHERROOTPATH=%ENV-ROOT%\bin\%PRODUCTNAME%
SET FRSITEROOTPATH=%LAUNCHERROOTPATH%\FR
SET ENSITEROOTPATH=%LAUNCHERROOTPATH%\EN
IF NOT EXIST "%LAUNCHERROOTPATH%" MKDIR "%LAUNCHERROOTPATH%"
IF NOT EXIST "%FRSITEROOTPATH%" MKDIR "%FRSITEROOTPATH%"
IF NOT EXIST "%ENSITEROOTPATH%" MKDIR "%ENSITEROOTPATH%"

copy /Y "%BATCH%\WySeMan.bat" "%FRSITEROOTPATH%" >> %LOG% 2>&1
copy /Y "%BATCH%\WySeMan.bat" "%ENSITEROOTPATH%" >> %LOG% 2>&1
xcopy "%CONFIGWSMFRSOURCE%\*" "%FRSITEROOTPATH%" /E /R /C /I /Y /H /G >> %LOG% 2>&1
xcopy "%CONFIGWSMENSOURCE%\*" "%ENSITEROOTPATH%" /E /R /C /I /Y /H /G >> %LOG% 2>&1
call %BATCH%\repl_in_file.bat "%FRSITEROOTPATH%\WySeMan.bat" {SERVER_PORT} %SERVER_PORT%
call %BATCH%\repl_in_file.bat "%FRSITEROOTPATH%\WNETCONF.ini" {WYDE_ROOT} %WYDE-ROOT%
call %BATCH%\repl_in_file.bat "%FRSITEROOTPATH%\WNETCONF.ini" {GSP_ALIAS} %GSP_ALIAS%
call %BATCH%\repl_in_file.bat "%FRSITEROOTPATH%\WNETCONF.ini" {GSP_CONFIG_FILE} %GSP_CONFIG_FILE%
call %BATCH%\repl_in_file.bat "%ENSITEROOTPATH%\WySeMan.bat" {SERVER_PORT} %SERVER_PORT%
call %BATCH%\repl_in_file.bat "%ENSITEROOTPATH%\WNETCONF.ini" {WYDE_ROOT} %WYDE-ROOT%
call %BATCH%\repl_in_file.bat "%ENSITEROOTPATH%\WNETCONF.ini" {GSP_ALIAS} %GSP_ALIAS%
call %BATCH%\repl_in_file.bat "%ENSITEROOTPATH%\WNETCONF.ini" {GSP_CONFIG_FILE} %GSP_CONFIG_FILE%

echo to launch easily Wyseman, execute the following batch :
echo %FRSITEROOTPATH%\WySeMan.bat
echo %ENSITEROOTPATH%\WySeMan.bat