
SET INSTALLIISRETURNCODE=0
SET bSITEALREADYEXIST=FALSE
SET bAPPPOOLALREADYEXIST=FALSE

::IF "%GSP_HANDLER_VERBS%"=="" SET GSP_HANDLER_VERBS=GET,HEAD,POST

ECHO #INFO# %~0 starting...
SET TMPSITEINFOFILE=%WF-Tmp%\siteinfo.xml

:: removing web site and APPPOOL_FR if exist
%APPCMD% list site %SITENAMEFR% > "%TMPSITEINFOFILE%"
SET ERRORLEVEL=0
IF EXIST "%TMPSITEINFOFILE%" FOR /F %%I IN (%TMPSITEINFOFILE%) DO IF "%%I"=="%SITENAMEFR%" SET bSITEALREADYEXIST=TRUE
%APPCMD% list APPPOOL_FR %APPPOOL_FR% > %TMPSITEINFOFILE%
SET ERRORLEVEL=0
IF EXIST "%TMPSITEINFOFILE%" FOR /F %%I IN (%TMPSITEINFOFILE%) DO IF "%%I"=="%SITENAMEFR%" SET bAPPPOOL_FRALREADYEXIST=TRUE
IF %bSITEALREADYEXIST%==TRUE CALL :REMOVEWEBSITE
IF %bAPPPOOLALREADYEXIST%==TRUE CALL :REMOVEAPPPOOL
IF NOT EXIST "%SITEDIRFR%" MKDIR "%SITEDIRFR%"
IF NOT %ERRORLEVEL%==0 SET INSTALLIISRETURNCODE=%ERRORLEVEL%
IF NOT %INSTALLIISRETURNCODE%==0 GOTO ENDINERROR

echo #INFO# Configuring IIS
::call %BATCH%\repl_in_file.bat "%GSPFOLDERTARGET%\WNETCONF.INI" {GSP_ALIAS} %GSP_ALIAS%
::call %BATCH%\repl_in_file.bat "%GSPFOLDERTARGET%\WNETCONF.INI" {SERVER_PORT_GSP} %SERVER_PORT%
::call %BATCH%\repl_in_file.bat "%GSPFOLDERTARGET%\WNETCONF.INI" {SERVER_PORT_WS} %SERVER_PORT%
::call %BATCH%\repl_in_file.bat "%GSPFOLDERTARGET%\WNETCONF.INI" {WYDE_ROOT} %WYDE-ROOT%

echo #INFO# Create and configure APPPOOL_FR %APPPOOL_FR%
CALL :ADDAPPPOOL_FR %APPPOOL_FR%
IF NOT %INSTALLIISRETURNCODE%==0 GOTO ENDINERROR

echo #INFO# Create and configure site %SITENAMEFR%
CALL :ADDSITE %SITENAMEFR% %APPPOOL_FR%
IF NOT %INSTALLIISRETURNCODE%==0 GOTO ENDINERROR
GOTO CLEANBEFOREEXIT

:REMOVEWEBSITE
ECHO #INFO# Removing existing site %SITENAMEFR% and delete file %SITEDIRFR%\web.config
%APPCMD% delete site "%SITENAMEFR%/"
IF NOT %ERRORLEVEL%==0 SET INSTALLIISRETURNCODE=%ERRORLEVEL%
IF EXIST %SITEDIRFR%\web.config del /Q /F %SITEDIRFR%\web.config
IF NOT %ERRORLEVEL%==0 SET INSTALLIISRETURNCODE=%ERRORLEVEL%
GOTO :EOF

:REMOVEAPPPOOL
ECHO #INFO# Removing existing APPPOOL %APPPOOL_FR%
%APPCMD% delete APPPOOL "%APPPOOL_FR%"
IF NOT %ERRORLEVEL%==0 SET INSTALLIISRETURNCODE=%ERRORLEVEL%
GOTO :EOF

:ADDSITE
echo #INFO# Create site %1
%APPCMD% add site /name:"%1" /physicalPath:%SITEDIRFR%
IF NOT %ERRORLEVEL%==0 SET INSTALLIISRETURNCODE=%ERRORLEVEL%

echo #INFO# Add APPPOOL_FR %2 to site %1
%APPCMD% set app /app.name:"%1/" /applicationPool:"%2"
IF NOT %ERRORLEVEL%==0 SET INSTALLIISRETURNCODE=%ERRORLEVEL%

echo #INFO# Add Port number %PORT_FR% to site %1
%APPCMD% set site /site.name:"%1" /+bindings.[protocol='http',bindingInformation='*:%PORT_FR%:']
IF NOT %ERRORLEVEL%==0 SET INSTALLIISRETURNCODE=%ERRORLEVEL%

::echo #INFO# Add handler %GSP_HANDLER_NAME%_%SITENAMEFR% to site %1
::IF "%BINVER%"=="Win32" SET ADDHANDLE32PRECONDITION=,preCondition='bitness32'
::%APPCMD% set config "%1/" /section:handlers /+[name='%GSP_HANDLER_NAME%_%SITENAMEFR%',path='%GSP_HANDLER_EXT%',verb='%GSP_HANDLER_VERBS%',modules='IsapiModule',scriptProcessor='%GSPDLL%',resourceType='Unspecified',requireAccess='Script'%ADDHANDLE32PRECONDITION%] /commit:site
::IF NOT %ERRORLEVEL%==0 SET INSTALLIISRETURNCODE=%ERRORLEVEL%

::echo #INFO# Remove if exist handler %GSP_HANDLER_NAME%_%SITENAMEFR% from isapiCgiRestriction
::ECHO %APPCMD% set config "/" /section:isapiCgiRestriction "/-[description='%GSP_HANDLER_NAME%_%SITENAMEFR%']"
::%APPCMD% set config "/" /section:isapiCgiRestriction "/-[description='%GSP_HANDLER_NAME%_%SITENAMEFR%']"
::IF NOT %ERRORLEVEL%==0 SET INSTALLIISRETURNCODE=%ERRORLEVEL%

::echo #INFO# Add handler %GSP_HANDLER_NAME% to isapiCgiRestriction
::%APPCMD% set config "/" /section:isapiCgiRestriction /+[path='%GSPDLL%',description='%GSP_HANDLER_NAME%_%SITENAMEFR%',allowed='True']
::IF NOT %ERRORLEVEL%==0 SET INSTALLIISRETURNCODE=%ERRORLEVEL%

::echo #INFO# Add index.html file on default web.config
::%APPCMD% set config "%1/" /section:defaultDocument "/-files.[value='index.html']"
::IF NOT %ERRORLEVEL%==0 SET INSTALLIISRETURNCODE=%ERRORLEVEL%
::%APPCMD% set config "%1/" /section:defaultDocument "/+files.[value='index.html']"
::IF NOT %ERRORLEVEL%==0 SET INSTALLIISRETURNCODE=%ERRORLEVEL%
::%APPCMD% set config "%1/" /section:defaultDocument "/-files.[value='default.aspx']"                
::IF NOT %ERRORLEVEL%==0 SET INSTALLIISRETURNCODE=%ERRORLEVEL%

::echo #INFO# Adding virtual directories (%VIRTUAL_DIR_LIST%) to web site %1
::for %%P in (%VIRTUAL_DIR_LIST%) do %APPCMD% add vdir /app.name:"%1/" /path:"/%%P" /physicalPath:"%VIRTUAL_DIR%"
::IF NOT %ERRORLEVEL%==0 SET INSTALLIISRETURNCODE=%ERRORLEVEL%
GOTO :EOF

:ADDAPPPOOL_FR
ECHO #INFO# Add APPPOOL %1
%APPCMD% add APPPOOL /name:%1
ECHO #INFO# Set APPPOOL_FR autostart
%APPCMD% set config -section:applicationPools -[name='%1'].autoStart:true
IF NOT %ERRORLEVEL%==0 SET INSTALLIISRETURNCODE=%ERRORLEVEL%
call %BATCH%\get_arch.bat
IF "%ARCH%"=="AMD64" IF "%BINVER%"=="Win32" ECHO #INFO# Set APPPOOL_FR enable32BitAppOnWin64
IF "%ARCH%"=="AMD64" IF "%BINVER%"=="Win32" %APPCMD% set config -section:applicationPools -[name='%1'].enable32BitAppOnWin64:true
IF NOT %ERRORLEVEL%==0 SET INSTALLIISRETURNCODE=%ERRORLEVEL%
GOTO :EOF

:ENDINERROR
ECHO #ERROR# %~0 ended in error with return code %INSTALLIISRETURNCODE%. Please check log file %LOG% and retry.
GOTO CLEANBEFOREEXIT

:CLEANBEFOREEXIT
IF EXIST "%TMPSITEINFOFILE%" DEL /Q /F "%TMPSITEINFOFILE%"
GOTO END

:END
ECHO #INFO# End of %~n0 with return code %INSTALLIISRETURNCODE%
EXIT /B %INSTALLIISRETURNCODE%