SET INSTALLRETURNCODE=0
echo Installation starting...
::call %BATCH%\copy_binaries.bat
::IF NOT %ERRORLEVEL%==0 SET INSTALLRETURNCODE=%ERRORLEVEL%
::IF NOT %INSTALLRETURNCODE%==0 GOTO ENDINERROR

xcopy "%CONFIGWEBSITEFRSOURCE%\WNETCONF.XML" "%SITEDIRFR%" /E /R /C /I /Y /H /G >> %LOG% 2>&1
xcopy "%CONFIGWEBSITEFRSOURCE%\Options.txt" "%SITEDIRFR%" /E /R /C /I /Y /H /G >> %LOG% 2>&1
xcopy "%CONFIGWEBSITEUSSOURCE%\WNETCONF.XML" "%SITEDIRUS%" /E /R /C /I /Y /H /G >> %LOG% 2>&1
xcopy "%CONFIGWEBSITEUSSOURCE%\Options.txt" "%SITEDIRUS%" /E /R /C /I /Y /H /G >> %LOG% 2>&1
IF NOT %ERRORLEVEL%==0 SET INSTALLRETURNCODE=%ERRORLEVEL%
IF NOT %INSTALLRETURNCODE%==0 GOTO ENDINERROR

echo #Info# Giving value %SERVER_PORT% to template variable {SERVER_PORT_CLICKONCE} in %SITEDIRFR%\WySeMan.bat
call %BATCH%\repl_in_file.bat "%SITEDIRFR%\WNETCONF.XML" {SERVER_PORT_CLICKONCE} %SERVER_PORT%
call %BATCH%\repl_in_file.bat "%SITEDIRUS%\WNETCONF.XML" {SERVER_PORT_CLICKONCE} %SERVER_PORT%

call %BATCH%\install_IIS_ClickOnce_US.bat
call %BATCH%\install_IIS_ClickOnce_FR.bat
IF NOT %ERRORLEVEL%==0 SET INSTALLRETURNCODE=%ERRORLEVEL%
IF NOT %INSTALLRETURNCODE%==0 GOTO ENDINERROR
echo Installation successfull
GOTO END

:ENDINERROR
ECHO #ERROR# %~0 ended with return code %INSTALLRETURNCODE%. Please check log file %LOG% and retry.
GOTO END

:END
EXIT /B %INSTALLRETURNCODE%