SET INSTALLRETURNCODE=0
echo Installation starting...
call %BATCH%\copy_binaries.bat
IF NOT %ERRORLEVEL%==0 SET INSTALLRETURNCODE=%ERRORLEVEL%
IF NOT %INSTALLRETURNCODE%==0 GOTO ENDINERROR

xcopy "%CONFIGGSPSOURCE%\WNETCONF.INI" "%GSPFOLDERTARGET%" /E /R /C /I /Y /H /G >> %LOG% 2>&1
IF NOT %ERRORLEVEL%==0 SET INSTALLRETURNCODE=%ERRORLEVEL%
IF NOT %INSTALLRETURNCODE%==0 GOTO ENDINERROR

call %BATCH%\install_IIS.bat
IF NOT %ERRORLEVEL%==0 SET INSTALLRETURNCODE=%ERRORLEVEL%
IF NOT %INSTALLRETURNCODE%==0 GOTO ENDINERROR
echo Installation successfull
GOTO END

:ENDINERROR
ECHO #ERROR# %~0 ended with return code %INSTALLRETURNCODE%. Please check log file %LOG% and retry.
GOTO END

:END
EXIT /B %INSTALLRETURNCODE%