@echo off

set BINVER=%1
set PORT=%2
set SERVER_PORT=%3
SET USERNAME=%4
SET PRODUCTNAME=SoapAPI
set GSP_HANDLER_EXT=*.gold
set GSP_HANDLER_NAME=GOLD_WS
SET GSP_CONFIG_FILE=SoapAPIConf.cfg

CALL %~dp0..\Install_WebServices.bat %PRODUCTNAME%
EXIT /B %ERRORLEVEL%
