SET INSTALLWEBSERVICESRETURNCODE=0
SET PRODUCTNAME=%1
SET PREFIXE=%PRODUCTNAME%WebServices

call %~dp0..\batch\Config_env_WebServices.bat
IF NOT %ERRORLEVEL%==0 SET INSTALLWEBSERVICESRETURNCODE=%ERRORLEVEL%
call %BATCH%\create_log.bat
IF NOT %ERRORLEVEL%==0 SET INSTALLWEBSERVICESRETURNCODE=%ERRORLEVEL%
call %BATCH%\check_env.bat
IF NOT %ERRORLEVEL%==0 SET INSTALLWEBSERVICESRETURNCODE=%ERRORLEVEL%
IF NOT %INSTALLWEBSERVICESRETURNCODE%==0 GOTO ERRORINSTALL

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::
IF "%BINVER%"=="" GOTO LAUNCHERROR
IF "%PORT%"=="" GOTO LAUNCHERROR
IF "%SERVER_PORT%"=="" GOTO LAUNCHERROR
IF "%USERNAME%"=="" GOTO LAUNCHERROR
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
set SITENAME=%USERNAME%_%PREFIXE%%PORT%
set VIRTUAL_DIR_LIST=%SITENAME%
set APPPOOL=%PREFIXE%AppPool%PORT%
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

ECHO *********************************************
ECHO Main local variables :
ECHO PRODUCTNAME : %PRODUCTNAME%
ECHO USERNAME : %USERNAME%
ECHO BINVER : %BINVER%
ECHO PORT : %PORT%
ECHO SERVER_PORT : %SERVER_PORT%
ECHO SITENAME : %SITENAME%
ECHO APPPOOL : %APPPOOL%
ECHO VIRTUAL_DIR_LIST : %VIRTUAL_DIR_LIST%
ECHO BATCH : %BATCH%
ECHO GSP_HANDLER_EXT : %GSP_HANDLER_EXT%
ECHO GSP_HANDLER_NAME : %GSP_HANDLER_NAME%
ECHO GSP_CONFIG_FILE : %GSP_CONFIG_FILE%
ECHO *********************************************

call %BATCH%\launch_install.bat
IF NOT %ERRORLEVEL%==0 SET INSTALLWEBSERVICESRETURNCODE=%ERRORLEVEL%
call %BATCH%\create_launchers_WS.bat
IF NOT %ERRORLEVEL%==0 SET INSTALLWEBSERVICESRETURNCODE=%ERRORLEVEL%
IF NOT %INSTALLWEBSERVICESRETURNCODE%==0 GOTO ERRORINSTALL
start %ENV-ROOT%\bin\%PRODUCTNAME%
GOTO END


:ERRORINSTALL
echo #ERROR# Installation failed
GOTO END

:LAUNCHERROR
SET INSTALLWPORTALRETURNCODE=1
echo #ERROR# Launch error : install_%PREFIXE% [BINVER] [PORT] [SERVER_PORT] [USERNAME]
echo #ERROR# Please choose IIS Port, WSM Port and type your first name
GOTO END

:END
exit /B %INSTALLWEBSERVICESRETURNCODE%
