@echo off
set BINVER=%1
set PORT=%2
set SERVER_PORT=%3
SET USERNAME=%4

SET PRODUCTNAME=RestAPI
set GSP_HANDLER_EXT=/api/*
set GSP_HANDLER_NAME=RESTAPI
set GSP_HANDLER_VERBS=*
SET GSP_CONFIG_FILE=RestAPIConf.cfg

CALL %~dp0..\Install_WebServices.bat %PRODUCTNAME%
EXIT /B %ERRORLEVEL%
