@ECHO OFF

SET CREATEOURETURNCODE=0
SET CREATEOULOGFILE=CreateOULink.log
SET ACTIVEDIRECTORYPARAMETERS=ActiveDirectoryMainInformations.txt

ECHO #INFO# Starting %~nx0 > %CREATEOULOGFILE%

IF NOT EXIST "%ACTIVEDIRECTORYPARAMETERS%" CALL :FILENOTFOUNDERROR "%ACTIVEDIRECTORYPARAMETERS%"
CALL :READMAINPARAMETERS
CALL :CHECKPARAMETERS
IF NOT %CREATEOURETURNCODE%==0 GOTO ENDINERROR

CALL :DSADDWYNGROUP
CALL :DSADDWYNUSER
IF NOT %CREATEOURETURNCODE%==0 GOTO ENDINERROR
GOTO END

:READMAINPARAMETERS
FOR /F "tokens=1,2 delims= " %%I IN (%ACTIVEDIRECTORYPARAMETERS%) DO SET %%I=%%J
GOTO :EOF

:CHECKPARAMETERS
IF "%AD_WYNUSER%"=="" ECHO #ERROR# Parameter AD_WYNUSER needed and does not exist
IF "%AD_WYNGROUP%"=="" ECHO #ERROR# Parameter AD_WYNGROUP needed and does not exist
IF "%AD_WYNUSER%"=="" SET CREATEOURETURNCODE=1
IF "%AD_WYNGROUP%"=="" SET CREATEOURETURNCODE=1
ECHO #INFO# AD_WYNUSER : %AD_WYNUSER%
ECHO #INFO# AD_WYNGROUP : %AD_WYNGROUP%
GOTO :EOF

:FILENOTFOUNDERROR
ECHO #ERROR# File not found : %1. Please check and retry.
SET CREATEGROUPSRETURNCODE=1
GOTO END

:DSADDWYNGROUP
ECHO #INFO# Adding group %AD_WYNGROUP% on domain %AD_WYNSUREDOMAIN%>> %CREATEOULOGFILE% 2>&1
ECHO dsadd ou %AD_WYNGROUP%,%AD_WYNSUREDOMAIN%>> %CREATEOULOGFILE% 2>&1
dsadd ou %AD_WYNGROUP%,%AD_WYNSUREDOMAIN%>> %CREATEOULOGFILE% 2>&1
IF NOT %ERRORLEVEL%==0 SET CREATEOURETURNCODE=%ERRORLEVEL%
GOTO :EOF

:DSADDWYNUSER
ECHO #INFO# Adding group %AD_WYNUSER% on domain %AD_WYNSUREDOMAIN%>> %CREATEOULOGFILE% 2>&1
ECHO dsadd ou %AD_WYNUSER%,%AD_WYNSUREDOMAIN%>> %CREATEOULOGFILE% 2>&1
dsadd ou %AD_WYNUSER%,%AD_WYNSUREDOMAIN%>> %CREATEOULOGFILE% 2>&1
IF NOT %ERRORLEVEL%==0 SET CREATEOURETURNCODE=%ERRORLEVEL%
GOTO :EOF

:ENDINERROR
ECHO ============= LOG CONTENT : ===================
TYPE %CREATEOULOGFILE%
ECHO .
ECHO ===============================================
ECHO #ERROR# %~nx0 ended in failure with return code %CREATEOURETURNCODE%. Please check the log %CREATEOULOGFILE%.
GOTO END

:END
ECHO End of %~nx0. Return code : %CREATEOURETURNCODE%
PAUSE
EXIT /B %CREATEOURETURNCODE%